### ISSUE TITLE
This can not be made on Linux/Ubuntu.

### ISSUE THREAD

**Issue by Colotov-Mocktail** [seresharp/HollowKnight.Modding#37]
Sadly, this can not be compiled/build on linux, as the netframe work you are using, 3.5, is not available on linux. Even if it were, the commands you are giving do not work.
linux does not have a msbuild command, but instead, a dotnet build command. And even if you were to go into the project file, and change it from 3.5, to a 5, you get a new error instead, saying the version string was either too long, or too short. And this is all with the release variant of this api. If you instead clone the git, the version difference can be fixed, but you run into a whole new set of problems. I hope this gets fixed soon

The error you get, if you instad clone this git, change the version to v5, you get this error.
(37,9): error MSB3073: The command "mono PrePatcher.exe Assembly-CSharp.dll Assembly-CSharp-patched.dll" exited with code 1.

I will note, that the guide does mention to instead run wine instead of mono, but i don't know how to do that

**Comment by iamwyza** [comment]
Correct.  .Net 5 is not the successor to .net 4.5.  .Net 5 is actually the successor to dotnet core 3.1.  They are completely and fundamentally different .net frameworks.  Since we're modding a game that is based on .net not dotnet core, it makes sense that you can't use dotnet core to build the mod framework without using wine / mono. (because there is no official .net 3.x/4.x builds for linux based OSes)   Wine is a windows compatibility layer.  I am not going to go into how it works here as there are numerous resources available on how to install Wine in whatever your linux system of choice is.

I can't see this *ever* being natively buildable on linux.  The game isn't going to get updated to run on dotnet core and thus neither is the modding framework.  You might be able

**Comment by fifty-six** [comment]
I'd also like to note that you *can* build on linux. You restore the packages via `dotnet restore` and then simply `msbuild .`. The prepatcher also doesn't need wine to run, but some people have found that to work better. I've built it without it on linux myself.

**Comment by fifty-six** [comment]
I built it again to make sure and I had an issue with LINQ throwing a MissingMethodException when run from the csproj. I've fixed the csproj on my fork, but it [works now](https://asciinema.org/a/n647peH4Qwc52vHHFyCCMJzvP). If you want to built it, my fork [is here](https://github.com/fifty-six/HollowKnight.Modding).
